-- =============================================================================
-- Flyway Migration V1: Initialize Relational E-Commerce Schema
-- Compatible with Oracle Database 23c and H2 (MODE=Oracle)
-- =============================================================================

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    slug VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(500),
    icon_name VARCHAR2(50)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    sku VARCHAR2(64) NOT NULL UNIQUE,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(2000),
    price NUMBER(10, 2) NOT NULL,
    image_url VARCHAR2(500),
    is_featured BOOLEAN DEFAULT FALSE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE inventories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL UNIQUE REFERENCES products(id),
    quantity_available NUMBER(10) NOT NULL,
    quantity_reserved NUMBER(10) DEFAULT 0 NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_qty_avail CHECK (quantity_available >= 0),
    CONSTRAINT chk_qty_resv CHECK (quantity_reserved >= 0)
);

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(255) NOT NULL,
    phone VARCHAR2(50),
    address_line1 VARCHAR2(255),
    city VARCHAR2(100),
    postal_code VARCHAR2(20),
    is_guest BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE carts (
    id VARCHAR2(64) PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id VARCHAR2(64) NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity NUMBER(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_cart_item_qty CHECK (quantity > 0),
    CONSTRAINT uk_cart_product UNIQUE (cart_id, product_id)
);

CREATE TABLE orders (
    id VARCHAR2(64) PRIMARY KEY,
    order_number VARCHAR2(32) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    status VARCHAR2(32) NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL,
    tax NUMBER(10, 2) DEFAULT 0.00 NOT NULL,
    shipping NUMBER(10, 2) DEFAULT 0.00 NOT NULL,
    total NUMBER(10, 2) NOT NULL,
    shipping_name VARCHAR2(255) NOT NULL,
    shipping_address VARCHAR2(255) NOT NULL,
    shipping_city VARCHAR2(100) NOT NULL,
    shipping_postal_code VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR2(64) NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity NUMBER(10) NOT NULL,
    unit_price NUMBER(10, 2) NOT NULL,
    total_price NUMBER(10, 2) NOT NULL,
    CONSTRAINT chk_order_item_qty CHECK (quantity > 0)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR2(64) NOT NULL REFERENCES orders(id),
    payment_method VARCHAR2(32) NOT NULL,
    status VARCHAR2(32) NOT NULL,
    transaction_ref VARCHAR2(64) NOT NULL,
    amount NUMBER(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
