import { Cart, Category, Order, OrderTracking, Product } from '@/types';

export const PRESET_CATEGORIES: Category[] = [
  {
    id: 1,
    name: 'Electronics',
    slug: 'electronics',
    description: 'Cutting-edge gadgets, audio gear, and personal devices.',
    iconName: 'laptop',
  },
  {
    id: 2,
    name: 'Fashion & Apparel',
    slug: 'fashion',
    description: 'Curated clothing, accessories, and everyday modern wear.',
    iconName: 'shirt',
  },
  {
    id: 3,
    name: 'Home & Living',
    slug: 'home-living',
    description: 'Modern home accessories, decor, and smart kitchen essentials.',
    iconName: 'home',
  },
  {
    id: 4,
    name: 'Books & Media',
    slug: 'books-media',
    description: 'Bestsellers, technical guides, and creative inspiration.',
    iconName: 'book',
  },
  {
    id: 5,
    name: 'Sports & Fitness',
    slug: 'sports-fitness',
    description: 'Gear and equipment for active, healthy living.',
    iconName: 'activity',
  },
];

export const PRESET_PRODUCTS: Product[] = [
  {
    id: 1,
    sku: 'ELEC-WH1000',
    title: 'Aura Wireless Noise-Canceling Headphones',
    description: 'Studio-quality sound with adaptive active noise cancellation, 40-hour battery life, and ultra-plush memory foam earcups.',
    price: 199.99,
    imageUrl: '/images/image_1.webp',
    isFeatured: true,
    isActive: true,
    category: PRESET_CATEGORIES[0],
    stockAvailable: 50,
  },
  {
    id: 2,
    sku: 'ELEC-SW900',
    title: 'Pulse GPS Smart Fitness Watch',
    description: 'Track workouts, heart rate, sleep quality, and GPS routes with up to 10 days of continuous battery life.',
    price: 149.50,
    imageUrl: '/images/image_1.webp',
    isFeatured: true,
    isActive: true,
    category: PRESET_CATEGORIES[0],
    stockAvailable: 35,
  },
  {
    id: 3,
    sku: 'ELEC-KB75',
    title: 'Zenith 75% Mechanical Keyboard',
    description: 'Hot-swappable mechanical switches, custom acoustic foam, and vibrant per-key RGB backlighting.',
    price: 89.00,
    imageUrl: '/images/image_1.webp',
    isFeatured: false,
    isActive: true,
    category: PRESET_CATEGORIES[0],
    stockAvailable: 20,
  },
  {
    id: 4,
    sku: 'FASH-BAG-VINT',
    title: 'Artisan Vintage Leather Weekender (Rare Limited Stock)',
    description: 'Handcrafted full-grain leather duffle bag with brass hardware. Only 1 unit remaining in current workshop batch.',
    price: 289.00,
    imageUrl: '/images/image_1.webp',
    isFeatured: true,
    isActive: true,
    category: PRESET_CATEGORIES[1],
    stockAvailable: 1, // Limited concurrency test
  },
  {
    id: 5,
    sku: 'FASH-HOOD-BLK',
    title: 'Minimalist Heavyweight Cotton Hoodie',
    description: 'Custom 450 GSM organic French terry cotton with relaxed fit and double-stitched durability.',
    price: 74.00,
    imageUrl: '/images/image_1.webp',
    isFeatured: false,
    isActive: true,
    category: PRESET_CATEGORIES[1],
    stockAvailable: 40,
  },
  {
    id: 6,
    sku: 'FASH-SUN-01',
    title: 'Polarized Classic Tortoise Sunglasses',
    description: 'Handmade acetate frames with UV400 scratch-resistant polarized lenses.',
    price: 55.00,
    imageUrl: '/images/image_1.webp',
    isFeatured: false,
    isActive: true,
    category: PRESET_CATEGORIES[1],
    stockAvailable: 25,
  },
  {
    id: 7,
    sku: 'HOME-MUG-CER',
    title: 'Handmade Stoneware Ceramic Coffee Dripper & Mug',
    description: 'Artisanal speckled ceramic pour-over set designed for perfect extraction and heat retention.',
    price: 38.00,
    imageUrl: '/images/image_1.webp',
    isFeatured: true,
    isActive: true,
    category: PRESET_CATEGORIES[2],
    stockAvailable: 30,
  },
  {
    id: 8,
    sku: 'HOME-DIFF-US',
    title: 'Aroma Ultrasonic Essential Oil Diffuser',
    description: 'Whisper-quiet ambient diffuser with warm LED mood lighting and automatic shut-off safety.',
    price: 45.00,
    imageUrl: '/images/image_1.webp',
    isFeatured: false,
    isActive: true,
    category: PRESET_CATEGORIES[2],
    stockAvailable: 15,
  },
  {
    id: 9,
    sku: 'BOOK-SYS-DES',
    title: 'System Design Interview & Architecture Masterclass',
    description: 'Comprehensive guide to building resilient distributed systems and modern web architecture.',
    price: 42.50,
    imageUrl: '/images/image_1.webp',
    isFeatured: false,
    isActive: true,
    category: PRESET_CATEGORIES[3],
    stockAvailable: 100,
  },
  {
    id: 10,
    sku: 'SPRT-MAT-PRO',
    title: 'Eco-Grip Alignment Yoga Mat',
    description: 'Non-slip natural tree rubber mat with laser-etched alignment guides and carrying strap.',
    price: 62.00,
    imageUrl: '/images/image_1.webp',
    isFeatured: false,
    isActive: true,
    category: PRESET_CATEGORIES[4],
    stockAvailable: 22,
  },
];

export const PRESET_CART_DEFAULT: Cart = {
  cartId: 'preset-demo-cart',
  totalItems: 2,
  subtotal: 273.99,
  items: [
    {
      id: 101,
      productId: 1,
      title: 'Aura Wireless Noise-Canceling Headphones',
      sku: 'ELEC-WH1000',
      imageUrl: '/images/image_1.webp',
      unitPrice: 199.99,
      quantity: 1,
      lineTotal: 199.99,
    },
    {
      id: 102,
      productId: 5,
      title: 'Minimalist Heavyweight Cotton Hoodie',
      sku: 'FASH-HOOD-BLK',
      imageUrl: '/images/image_1.webp',
      unitPrice: 74.00,
      quantity: 1,
      lineTotal: 74.00,
    },
  ],
};

export const PRESET_ORDER_DEFAULT: Order = {
  orderId: 'demo-order-uuid-001',
  orderNumber: 'ORD-2026-DEMO01',
  status: 'PAYMENT_CONFIRMED',
  subtotal: 273.99,
  tax: 21.92,
  shipping: 0.0,
  total: 295.91,
  customerName: 'John Tester',
  customerEmail: 'john.tester@example.com',
  shippingAddress: '123 Showcase Boulevard, Suite 400',
  shippingCity: 'San Francisco',
  shippingPostalCode: '94105',
  paymentMethod: 'MOCK_CREDIT_CARD',
  paymentStatus: 'COMPLETED',
  transactionRef: 'TXN-MOCK-SIM-SUCCESS-9876',
  createdAt: new Date().toISOString(),
  items: [
    {
      id: 201,
      productId: 1,
      title: 'Aura Wireless Noise-Canceling Headphones',
      sku: 'ELEC-WH1000',
      imageUrl: '/images/image_1.webp',
      unitPrice: 199.99,
      quantity: 1,
      totalPrice: 199.99,
    },
    {
      id: 202,
      productId: 5,
      title: 'Minimalist Heavyweight Cotton Hoodie',
      sku: 'FASH-HOOD-BLK',
      imageUrl: '/images/image_1.webp',
      unitPrice: 74.00,
      quantity: 1,
      totalPrice: 74.00,
    },
  ],
};

export const PRESET_TRACKING_DEFAULT: OrderTracking = {
  orderNumber: 'ORD-2026-DEMO01',
  currentStatus: 'PAYMENT_CONFIRMED',
  currentStepIndex: 1,
  steps: [
    {
      status: 'PENDING',
      label: 'Order Placed',
      description: 'Order created and inventory reserved.',
      isCompleted: true,
      isCurrent: false,
    },
    {
      status: 'PAYMENT_CONFIRMED',
      label: 'Payment Confirmed',
      description: 'Transaction approved via mock payment gateway.',
      isCompleted: true,
      isCurrent: true,
    },
    {
      status: 'PROCESSING',
      label: 'Processing & Packing',
      description: 'Items picked from warehouse and packaged.',
      isCompleted: false,
      isCurrent: false,
    },
    {
      status: 'SHIPPED',
      label: 'In Transit',
      description: 'Carrier picked up order for courier delivery.',
      isCompleted: false,
      isCurrent: false,
    },
    {
      status: 'DELIVERED',
      label: 'Delivered',
      description: 'Delivered to customer address.',
      isCompleted: false,
      isCurrent: false,
    },
  ],
};
